### ISSUE TITLE
new version can not login in

### ISSUE THREAD

**Issue by hao13734228896** [carolcoral/free_vpn#4]
new version can not login in

**Comment by carolcoral** [comment]
@hao13734228896 I have updated it ,please download and try it agin,THX

**Comment by hao13734228896** [comment]
我这边用的mac，一直显示我们正在为您登录，尝试备份端点

**Comment by carolcoral** [comment]
@hao13734228896 查看mac中的系统设置，看看是不是系统禁用了该软件的网络或者其他操作，mac使用非AppStore的软件需要进行设置，否则会默认进行安全性校验（通常是非AppStore的都不能用）
