### ISSUE TITLE
现在完全挂了

### ISSUE THREAD

**Issue by huanyue6660** [carolcoral/free_vpn#6]

**Comment by carolcoral** [comment]
@huanyue6660 你好，请问是windows的还是安卓的，或者是两个都无法使用了

**Comment by hellowenqi** [comment]
macos 挂了

**Comment by carolcoral** [comment]
@huanyue6660 嗯，因为gw目前更新了，winscribe的部分用户已经无法使用了，你可以试试我才更新的bvpn，有几天的试用时间，可以先试试，后续会添加新的vpn，不过付费的会多一些，稳定性有保障的
