### ISSUE TITLE
windscribe让我的网络挂了

### ISSUE THREAD

**Issue by ChineseHero** [carolcoral/free_vpn#7]
windscribe让我的网络挂了，卸载后我来提出这个问题了。

**Comment by carolcoral** [comment]
@ChineseHero 因为目前winscribe确实会导致本地网络出现一些问题，这个要看人品了，因为我已经在win7、win8和win10上测试过确实可用的

**Comment by carolcoral** [comment]
@ChineseHero 目前有一款免费的vpn----bvpn已经更新了，有几天的试用时间，临时用用是可以的，后续会继续添加可用的vpn，不过付费的应该占多数了，欢迎star
