### ISSUE TITLE
linux下有没有试过？deepin系统或者是debian系统

### ISSUE THREAD

**Issue by bibichuan** [carolcoral/free_vpn#8]
我在deepin系统上安装了桌面端，想着通过switchomage控制国内的不走vpn，这样可以节省流量，可是一直显示
![image](https://user-images.githubusercontent.com/14054904/53299733-4f0d9800-3879-11e9-94a4-e6aad37e8289.png)
总是链接不上，还要继续努力吧。

**Comment by carolcoral** [comment]
@bibichuan 你用的是winscribe的还是bvpn的

**Comment by carolcoral** [comment]
@bibichuan 如果还是连接不上我个人是不建议继续尝试了，因为liunx的用户比较少，它的维护是比较欠缺的。如果临时使用可以建议去试试我才更新的bvpn，如果需要长期使用可以尝试稍后最新更新的两款vpn：banwagong和ss，欢迎star，以方便接受最新内容更新。

**Comment by bibichuan** [comment]
其实我windows下也没成功，只能在浏览器插件上使用。

**Comment by carolcoral** [comment]
@bibichuan 那我个人建议直接购买ss或者banwagong，然后在chrome上使用SwitchyOmega插件配置代理，到目前为止非常稳定可靠
